language: generic

sudo: false

git:
  submodules: false

cache:
  directories:
    - $HOME/.mafia

matrix:
  include:
  - env: GHCVER=8.0.2 CABALVER=1.24
    addons:
      apt:
        sources:
          - hvr-ghc
        packages:
          - ghc-8.0.2
          - cabal-install-1.24
  - env: GHCVER=8.0.2 CABALVER=2.0
    addons:
      apt:
        sources:
          - hvr-ghc
        packages:
          - ghc-8.0.2
          - cabal-install-2.0
  - env: GHCVER=8.2.1 CABALVER=1.24
    addons:
      apt:
        sources:
          - hvr-ghc
        packages:
          - ghc-8.2.1
          - cabal-install-1.24
  - env: GHCVER=8.2.1 CABALVER=2.0
    addons:
      apt:
        sources:
          - hvr-ghc
        packages:
          - ghc-8.2.1
          - cabal-install-2.0
  # mafia doesnt build with ghc-8.4.1
  #- env: GHCVER=8.4.1 CABALVER=1.24
  #  addons:
  #    apt:
  #      sources:
  #        - hvr-ghc
  #      packages:
  #        - ghc-8.4.1
  #        - cabal-install-1.24
  #- env: GHCVER=8.4.1 CABALVER=2.0
  #  addons:
  #    apt:
  #      sources:
  #        - hvr-ghc
  #      packages:
  #        - ghc-8.4.1
  #        - cabal-install-2.0
  #allow-failures:
  #  - env: GHCVER=head
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.2
      - libgmp-dev

before_install:
  # ghc
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

script:
  - bin/ci
